Feature: setup parser
ditrit/terrator-plugin pull request #4
Opened 2022-08-26 13:22 UTC by Zorin95670

2022-08-26 14:56 UTC, Hundraw submitted a review, later dismissed

2022-08-26 15:51 UTC, k-y0u requested changes

2022-08-26 15:51 UTC, k-y0u commented on src/parser/TerraformListener.js
> +  enterFile() {
why empty ?

2022-08-26 15:51 UTC, k-y0u commented on src/parser/TerraformParser.js
> +              && attribute.definition.type === 'Reference'
indent

2022-08-26 15:51 UTC, k-y0u commented on src/parser/TerraformParser.js
> +   * Indicate if a component is can have parent.
`is can` -> `can`

2022-08-26 15:51 UTC, k-y0u commented on tests/unit/parser/TerraformParser.spec.js
> +        it('test multiple default link', () => {
multiple -> linkS

2022-08-26 15:51 UTC, k-y0u commented on tests/unit/parser/TerraformParser.spec.js
> +        it('test multiple reverse link', () => {
Same here

2022-08-29 07:42 UTC, Zorin95670 commented on src/parser/TerraformListener.js
> +  enterFile() {
It's generated method from grammar.

2022-08-29 07:43 UTC, Zorin95670 commented on src/parser/TerraformParser.js
> +              && attribute.definition.type === 'Reference'
done

2022-08-29 07:43 UTC, Zorin95670 commented on src/parser/TerraformParser.js
> +   * Indicate if a component is can have parent.
done

2022-08-29 07:44 UTC, Zorin95670 commented on tests/unit/parser/TerraformParser.spec.js
> +        it('test multiple default link', () => {
done

2022-08-29 07:44 UTC, Zorin95670 commented on tests/unit/parser/TerraformParser.spec.js
> +        it('test multiple reverse link', () => {
done

2022-08-29 08:21 UTC, Hundraw submitted a review, later dismissed

2022-08-29 12:16 UTC, k-y0u submitted a review, later dismissed

2022-08-30 07:34 UTC, k-y0u commented on tests/unit/parser/TerraformParser.spec.js
> +        it('test single default link', () => {
From here, the `it()` (all of them) should contain sentence which explains the verification (like above).
For instance:
`it("should parse a default link")`

2022-08-30 08:16 UTC, k-y0u approved these changes

2022-08-30 08:32 UTC, merged