Bugfix: missing attribute definition
ditrit/terrator-plugin pull request #49
Opened 2023-01-20 13:39 UTC by Zorin95670

Resolved #48

2023-01-20 13:50 UTC, justinehell submitted a review, later dismissed

2023-01-20 13:53 UTC, k-y0u requested changes

2023-01-20 13:53 UTC, k-y0u commented on src/parser/TerraformListener.js
> +    let definition;
why do you use a variable ?

2023-01-20 13:53 UTC, k-y0u commented on src/parser/TerraformListener.js
> +    this.currentField.definition = definition;
why do that just before
`this.currentField = null;`

2023-01-23 10:18 UTC, k-y0u approved these changes

2023-01-23 10:19 UTC, merged