Feature: use file models
ditrit/terrator-plugin pull request #7
Opened 2022-09-01 15:08 UTC by Zorin95670

2022-09-02 14:47 UTC, Hundraw approved these changes

2022-09-02 14:56 UTC, k-y0u requested changes

2022-09-02 14:56 UTC, k-y0u commented on src/parser/TerraformParser.js
> +   * @param {FileInformation} [fileName] - Name of file.
All should be change, not only the type.

2022-09-02 14:56 UTC, k-y0u commented on src/render/TerraformRenderer.js
> +   * @return {FileInput[]} - Array of generated file content from components and links.
`file content` -> `files`

2022-09-02 14:56 UTC, k-y0u commented on src/render/TerraformRenderer.js
> +  render(componentsTree, links, defaultFileName = './new_file.tf') {
missing description for the new param.

2022-09-02 14:56 UTC, k-y0u commented on src/render/TerraformRenderer.js
> +    map.forEach((components, path) => {
`return Array.map()` should avoid 2 lines

2022-09-06 08:21 UTC, k-y0u requested changes

2022-09-06 08:21 UTC, k-y0u commented on src/parser/TerraformListener.js
> +  constructor(definitions) {
no description for class and methods here

2022-09-06 08:23 UTC, k-y0u approved these changes

2022-09-06 08:23 UTC, merged