Bugfix/manage empty list attribute
ditrit/terrator-plugin pull request #79
Opened 2023-06-20 12:02 UTC by k-y0u

resolves #78

2023-06-20 13:01 UTC, viennem submitted a review, later dismissed
I confirm that the fix works.
I did not review the code.

2023-06-20 14:45 UTC, Zorin95670 requested changes

2023-06-20 14:45 UTC, Zorin95670 commented on tests/resources/tf/bug78_emptyListAttribute.tf
> +}
missing empty line at the end of file

2023-06-20 14:47 UTC, justinehell requested changes

2023-06-21 08:32 UTC, k-y0u commented on tests/resources/tf/bug78_emptyListAttribute.tf
> +}
Done

2023-06-21 08:32 UTC, k-y0u commented on tests/resources/tf/bug78_emptyListAttribute.tf
> +}
Done

2023-06-21 09:14 UTC, justinehell approved these changes

2023-06-21 09:15 UTC, merged